"""empty message

Revision ID: fb78e4568606
Revises: 3ddd159c2825
Create Date: 2024-06-21 10:15:23.355846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb78e4568606'
down_revision: Union[str, None] = '3ddd159c2825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title_index', 'vacancies', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title_index', table_name='vacancies')
    # ### end Alembic commands ###
